
.apt-template: &apt-template
- export LC_ALL=C.UTF-8
- export DEBIAN_FRONTEND=noninteractive
- echo Etc/UTC > /etc/timezone
- echo 'quiet "1";'
       'APT::Install-Recommends "0";'
       'APT::Install-Suggests "0";'
       'APT::Acquire::Retries "20";'
       'APT::Get::Assume-Yes "true";'
       'Dpkg::Use-Pty "0";'
      > /etc/apt/apt.conf.d/99gitlab
- apt-get update
- apt-get dist-upgrade
- apt-get install git


.artifacts-template: &artifacts-template
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - build/libs/
      - target/
    expire_in: 1 week
    when: always

  after_script:
    - echo "Download debug artifacts from https://gitlab.com/${CI_PROJECT_PATH}/-/jobs"


debian_buster:
  image: debian:buster
  <<: *artifacts-template
  script:
    - echo "deb http://deb.debian.org/debian/ buster-backports main" >> /etc/apt/sources.list
    - *apt-template
    - apt-get install tor/buster-backports
    - apt-get install default-jdk gradle junit4
    - gradle build jar sourcesJar javadocJar writeNewPom

openjdk-14:
  image: openjdk:14-buster
  <<: *artifacts-template
  script:
    - echo "deb http://deb.debian.org/debian/ buster-backports main" >> /etc/apt/sources.list
    - *apt-template
    - apt-get install tor/buster-backports
    - apt-get install gradle
    - gradle build jar sourcesJar javadocJar writeNewPom

openjdk-8:
  image: openjdk:8-stretch
  <<: *artifacts-template
  artifacts:
    paths:
      - build/libs
  script:
    - echo "deb http://deb.debian.org/debian/ stretch-backports-sloppy main" >> /etc/apt/sources.list
    - *apt-template
    - apt-get install tor/stretch-backports-sloppy
    - ./gradlew build jar sourcesJar javadocJar writeNewPom
    - for f in build/libs/*.jar; do sha256sum $f; done

openjdk-8_maven:
  image: openjdk:8-stretch
  <<: *artifacts-template
  artifacts:
    paths:
      - target/jtorctl-*.*
  script:
    - echo "deb http://deb.debian.org/debian/ stretch-backports-sloppy main" >> /etc/apt/sources.list
    - *apt-template
    - apt-get install maven tor/stretch-backports-sloppy
    - mvn verify
    - for f in target/*.jar; do sha256sum $f; done

pages:
  stage: deploy
  image: openjdk:8-stretch
  artifacts:
    paths:
      - public
  only:
    - tags
    # TODO figure out snapshot releases, this only works for tagged releases now
  script:
    - ./gradlew javadoc
    - test -d public || mkdir public
    - mv build/docs/javadoc/* public/

    - *apt-template
    - apt-get install maven
    - sed -i "s,CI_PROJECT_ID,${CI_PROJECT_ID},g" pom.xml
    - mvn versions:set -DnewVersion=$(git describe --tags --always)
    - mvn deploy -s .gitlab/mvn_settings.xml
    - for f in target/*.jar; do sha256sum $f; done
